apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg
  namespace: vaultwarden
  labels:
    app.kubernetes.io/name: warden
    app.kubernetes.io/component: pg
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: warden
      app.kubernetes.io/component: pg
  template:
    metadata:
      labels:
        app.kubernetes.io/name: warden
        app.kubernetes.io/component: pg
    spec:
      containers:
        - name: db-postgres
          image: postgres:15
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          ports:
            - containerPort: 5432
              name: postgres
