apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden
  namespace: vaultwarden
  labels:
    app.kubernetes.io/name: warden
    app.kubernetes.io/component: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: warden
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: warden
        app.kubernetes.io/component: web
    spec:
      containers:
        - name: web
          image: vaultwarden/server:1.30.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: DATABASE_URL
              value: postgresql://postgres:postgres@10.244.0.17:5432/postgres
